### ISSUE TITLE
gungame 1.3.0 counter-strike-source 

### ISSUE THREAD

**Issue by herlak** [GunGame-Dev-Team/GunGame-SP#12]
```
2019-08-09 06:09:07 - sp	-	MESSAGE	[SP] Chargement du plugin 'es_emulator'...
2019-08-09 06:09:08 - sp	-	MESSAGE	[SP] Le plugin 'es_emulator' a été chargé avec succès.
2019-08-09 06:09:09 - sp	-	MESSAGE	[SP] Chargement du plugin 'gungame'...
2019-08-09 06:09:11 - sp	-	MESSAGE	[SP] Le plugin 'gungame' a été chargé avec succès.
2019-08-09 06:09:11 - sp	-	MESSAGE	[SP] Chargement du plugin 'wcs'...
2019-08-09 06:09:12 - sp	-	MESSAGE	[SP] Le plugin 'wcs' a été chargé avec succès.
2019-08-09 06:09:20 - sp	-	MESSAGE	Sub command "reload" not found.
2019-08-09 06:16:17 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 92, in __getitem__
    return super().__getitem__(name)

KeyError: 'weapon_env_explosion'
```

**Comment by satoon101** [comment]
@herlak - Sorry for the very late response.  I have not really been active with Source.Python for a while, but am doing some fixes right now for GunGame.  Which game was this on?  And which map, if there was a specific map you were seeing this on?

**Comment by srpg** [comment]
@satoon101 I got the same error, game is cs:s. Map is gg_anem, its first time i saw this error.
